Add Document/Transaction/Contact types to the config vol 2
akaunting/akaunting pull request #1742
Opened 2021-01-09 19:45 UTC by cuneytsenturk

refs #1732 https://github.com/akaunting/akaunting/pull/1732/commits/3aa94bc9e273c9ae438636951d4bd46fad38dcc7

2021-01-09 19:46 UTC, cuneytsenturk commented
@denisdulici, @burakcakirel, @pavel-mironchik  Shall we discuss this over PR?

2021-01-10 09:16 UTC, denisdulici commented
It seems ok for me.

2021-01-10 11:19 UTC, pavel-mironchik commented on config/type.php
> +            'paramater' => 'invoice', // sales/invoices/{parameter}/edit
A typo, should be "parameter". Also below and in the `app/Http/Requests/Document/Document.php`.

2021-01-10 11:28 UTC, cuneytsenturk commented on config/type.php
> +            'paramater' => 'invoice', // sales/invoices/{parameter}/edit
Thank pavel I've changed.

2021-01-10 11:48 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +            if (!$module instanceof Module) {
Missing import `use Akaunting\Module\Module;`.

2021-01-10 11:51 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +            if (!$module instanceof Module) {
Also, it would be better to return an empty array, otherwise the `null` is returned and that causes an exception down the components chain.

2021-01-10 12:16 UTC, pavel-mironchik commented on app/Abstracts/View/Components/Document.php
> +        $route = $prefix . '.' . $config_key;
If it doesn't take into account the alias, then I have to set typical routes (show, edit, duplicate, etc.) in the config explicitly:

```
    'debit-note' => [
        'alias'        => 'credit-debit-notes',
        'group'        => '',
        'route'        => [
            'prefix'    => 'debit-notes',
            'parameter' => 'debit_note',
            'show' => 'credit-debit-notes.debit-notes.show',
            'edit' => 'credit-debit-notes.debit-notes.edit',
            'duplicate' => 'credit-debit-notes.debit-notes.duplicate',
            'cancelled' => 'credit-debit-notes.debit-notes.cancelled',
        ],
```

2021-01-10 12:43 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentIndex.php
> +            if (!$module instanceof Module) {
I am missing use class. I've fixed it.

2021-01-10 12:44 UTC, pavel-mironchik commented
@cuneytsenturk do you see the same in Bills?

![2021-01-10 18-41-37 Ubuntu Mate 19 10 (Снимок 192)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/104123184-c36d5980-5373-11eb-914e-a15e37862071.png)

2021-01-10 12:48 UTC, cuneytsenturk commented on app/Abstracts/View/Components/Document.php
> +        $route = $prefix . '.' . $config_key;
Pavel, I've looked your index.blade and you use `debit-notes.show` [here](https://github.com/akaunting/module-credit-debit-notes/blob/master/Resources/views/debit_notes/index.blade.php#L68)

2021-01-10 12:54 UTC, cuneytsenturk commented
> @cuneytsenturk do you see the same in Bills?
> 
> ![2021-01-10 18-41-37 Ubuntu Mate 19 10 (Снимок 192) Работает - Oracle VM VirtualBox 2](https://user-images.githubusercontent.com/7408605/104123184-c36d5980-5373-11eb-914e-a15e37862071.png)

@pavel-mironchik 
It looks like this on me

![bill-index](https://user-images.githubusercontent.com/10936547/104123389-0fac9f80-535c-11eb-891d-34d617086d69.PNG)

Do you do `composer update and npm run dev`?

2021-01-10 12:59 UTC, pavel-mironchik commented on app/Abstracts/View/Components/Document.php
> +        $route = $prefix . '.' . $config_key;
> Pavel, I've looked your index.blade and you use `debit-notes.show` [here](https://github.com/akaunting/module-credit-debit-notes/blob/master/Resources/views/debit_notes/index.blade.php#L68)

Yeah, you're right about this, and sorry for misleading you about this part. Actually, I was wrong when used "non-aliased" routes in my module. It's a really bad practice in the "multi-application" environment. Now, there is a chance for me to do things right, and I'm absolutely sure that all module's routes should be "aliased". Check this [routes file](https://github.com/akaunting/module-credit-debit-notes/blob/v110/Routes/admin.php), though it isn't finished yet.

2021-01-10 13:03 UTC, pavel-mironchik commented
> Do you do `composer update and npm run dev`?

Nope, only `composer install` and `npm install && npm run dev` to be sure that we have the same dependencies.

2021-01-10 13:06 UTC, cuneytsenturk commented on app/Abstracts/View/Components/Document.php
> +        $route = $prefix . '.' . $config_key;
@burakcakirel @denisdulici if it suits everyone, I will add it.

2021-01-10 13:09 UTC, pavel-mironchik commented
Anyway, the `composer update` says `Nothing to install, update or remove`, so we have the same packages' versions. Ok, nevermind, I will look into this later.

2021-01-10 13:11 UTC, denisdulici commented on app/Abstracts/View/Components/Document.php
> +        $route = $prefix . '.' . $config_key;
Agree, module routes are/should be aliased.

2021-01-10 13:11 UTC, cuneytsenturk commented
Okey, I've thinked livewire package not installed.

2021-01-10 13:31 UTC, cuneytsenturk commented on app/Abstracts/View/Components/Document.php
> +        $route = $prefix . '.' . $config_key;
Added it.

2021-01-10 15:43 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +        $prefix = Str::studly(Str::plural(config('type.' . $type . '.route.prefix'), 1));
This will generate a path with plurals, like `App\Models\Purchases\Bills` and `Modules\CreditDebitNotes\Models\DebitNotes`, whereas models in Laravel (and In the Sofware too, of course) [use the single form](https://github.com/akaunting/akaunting/blob/fb219f877eeea6abed8fe333062901673d2813cb/modules/BC21/Models/Purchase/Bill.php#L3-L12).

2021-01-10 15:48 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +        $prefix = Str::studly(Str::plural(config('type.' . $type . '.route.prefix'), 1));
I suppose that you were trying to get a singular form. In that case, the `Str::singular()` could help/

2021-01-10 16:00 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentIndex.php
> +        $prefix = Str::studly(Str::plural(config('type.' . $type . '.route.prefix'), 1));
I've changed it.

2021-01-10 16:16 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +            $group = Str::studly(Str::singular($group) . '\\';
You've missed a closing brace :)

$group = Str::studly(Str::singular($group)**)** . '\\';

2021-01-10 16:24 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentIndex.php
> +            $group = Str::studly(Str::singular($group) . '\\';
fixed it. missing `)` parameter

2021-01-10 16:49 UTC, pavel-mironchik commented
`php artisan optimize:clear` helped with enabling LiveWire.

2021-01-10 17:17 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +        $class = $this->getTextFromConfig($type, 'issued_at');
I suppose that this call and others in class-related methods should be `getClassFromConfig()` instead of the `getTextFromConfig()`.

2021-01-10 17:28 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +        $class = $this->getTextFromConfig($type, 'issued_at');
Ah, and that's why I see broken Bills table.

2021-01-10 17:37 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentIndex.php
> +        $class = $this->getTextFromConfig($type, 'issued_at');
I've changed all functon name issues.

2021-01-10 18:25 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +        return 'invoices.statuses.';
This still looks working in my environment only with the "invoice's statuses", but not with custom ones or at least with a bill's `received` status:
![2021-01-10 23-55-06 Ubuntu Mate 19 10 (Снимок 193)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/104131733-7bb1f680-53a2-11eb-9d12-78128d5e00f2.png)

The sophisticated algorithm of the `getTextFromConfig` method, in the end, falls to the default `invoices.statuses.` translation key.

@cuneytsenturk do you check this in your fork's master branch or in the upstream's master? I've checked out this PR and experience such an issue with the "received" status.

2021-01-10 18:33 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentShow.php
> +        $translation = $this->getTextFromConfig($type, 'timeline_sent_status_received', $default_key);
The `$default_key` variable isn't set. I guess it should be placed here instead of two `$textTimelineSentStatusReceived = ` statements.

2021-01-10 18:39 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentShow.php
> +        $translation = $this->getTextFromConfig($type, 'timeline_sent_status_received', $default_key);
I've fixed it.

2021-01-10 18:45 UTC, pavel-mironchik commented
If I'm not mistaken, we need the alias here too, so the route's name would be `credit-debit-notes.settings.debit-note.edit` instead of just `settings.debit-note.edit`. As I mentioned earlier, I've aliased routes recently in the upcoming release.
https://github.com/akaunting/akaunting/blob/b3b4c866fc89f6617eac38ec861c1d29c2e5a2b4/app/Abstracts/View/Components/DocumentShow.php#L764

2021-01-10 19:00 UTC, cuneytsenturk commented
> If I'm not mistaken, we need the alias here too, so the route's name would be `credit-debit-notes.settings.debit-note.edit` instead of just `settings.debit-note.edit`. As I mentioned earlier, I've aliased routes recently in the upcoming release.

yes I will add module prefix :)

2021-01-10 19:10 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentIndex.php
> +        return 'invoices.statuses.';
I've changed it. [here](https://github.com/akaunting/akaunting/pull/1742/commits/0f158cdc7eb81c35e00a92aee49175637b79edc0)

2021-01-11 06:26 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +        return 'invoices.statuses.';
Oh, I've just noticed that now Debit Notes table shows weird statuses:
![2021-01-11 12-23-30 Ubuntu Mate 19 10 (Снимок 196)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/104151686-dd587c00-5407-11eb-8b19-63c481358c8d.png)

This happens because the translation key is `debit_notes.statuses.` now, and we need an alias: `credit-debit-notes::debit_notes.statuses.`.

2021-01-11 08:11 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentIndex.php
> +        return 'invoices.statuses.';
Pavel, I've move documents file for document status and added module alias :)

2021-01-11 09:03 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +            if (is_array(trans($$translation))) {
Is this a typo? Double $ symbol here and in other files too.

2021-01-11 09:25 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentShow.php
> +        $default_key = 'create_' . $type;
We have to change this slightly. For example, when the `$type` is `debit-note`, we need to change hyphens for underscores, so a translation key would be `create_debit_note` (it will get the alias later).

2021-01-11 09:28 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentIndex.php
> +            if (is_array(trans($$translation))) {
I've fixed it.

2021-01-11 09:33 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentShow.php
> +        $default_key = 'create_' . $type;
I've changed.

2021-01-11 09:43 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +            if (is_array(trans($$translation))) {
> I've fixed it.

Thanks. Didn't you forget to change the Documents trait too?

2021-01-11 09:46 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentShow.php
> +        $default_key = 'create_' . str_replace('-', '_', config('type.' . $type . '.alias');
A closing brace is missing.

2021-01-11 09:47 UTC, burakcakirel commented on app/Abstracts/View/Components/DocumentIndex.php
> +            if (is_array(trans($$translation))) {
And also `DocumentShow`

2021-01-11 10:11 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentShow.php
> +        $default_key = 'create_' . str_replace('-', '_', config('type.' . $type . '.alias');
ohh, ı've fixed it.

2021-01-11 12:42 UTC, burakcakirel requested changes

2021-01-11 12:46 UTC, burakcakirel commented
I think it would be also better if we get `category_type` from the config for modules.
https://github.com/akaunting/akaunting/blob/master/app/View/Components/Documents/Form/Advanced.php#L28

2021-01-11 13:01 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentForm.php
> +            request()->get('invoiced_at', Date::now()->toDateString());
thanks burak, I've fixed.

2021-01-11 13:20 UTC, cuneytsenturk commented
> I think it would be also better if we get `category_type` from the config for modules.
> https://github.com/akaunting/akaunting/blob/master/app/View/Components/Documents/Form/Advanced.php#L28

I've added

2021-01-11 13:23 UTC, pavel-mironchik commented on app/Abstracts/View/Components/DocumentIndex.php
> +            if (is_array(trans($$translation))) {
> Thanks. Didn't you forget to change the Documents trait too?

@cuneytsenturk ?

2021-01-11 13:28 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentIndex.php
> +            if (is_array(trans($$translation))) {
ohh, I remember it, now it fixed. Thank Pavel.

2021-01-11 19:46 UTC, burakcakirel requested changes

2021-01-11 19:46 UTC, burakcakirel commented on app/Abstracts/View/Components/DocumentShow.php
> +        $translation = $this->getTextFromConfig($type, 'recurring_tye', $default_key);
typo in `recurring_tye`

2021-01-11 19:46 UTC, burakcakirel commented on app/Abstracts/View/Components/DocumentShow.php
> +        $default_key = config('type.' . $type . '.translation.prefix');
We should also apply the same changes in the following commits to here and all places that use `config('type.' . $type . '.translation.prefix')`, I think.
https://github.com/akaunting/akaunting/pull/1742/commits/265e3bbc6fc8a40e51f1d8f1f882a8642e533d93
https://github.com/akaunting/akaunting/pull/1742/commits/00ed7bcd49cc427cff53344161dcdf5e6af611db

2021-01-11 20:07 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentShow.php
> +        $default_key = config('type.' . $type . '.translation.prefix');
I've changed..

2021-01-11 20:07 UTC, cuneytsenturk commented on app/Abstracts/View/Components/DocumentShow.php
> +        $translation = $this->getTextFromConfig($type, 'recurring_tye', $default_key);
Already add recurrint_type tranlation key..

2021-01-11 21:28 UTC, merged