Format in the datepicker
akaunting/akaunting pull request #1821
Opened 2021-02-01 11:44 UTC by tognit

Would it be possible to output the format in the data picker based on the company setting?
As well as the language according to company settings

2021-02-02 08:16 UTC, denisdulici requested changes
Thanks for the contribution, I've added some comments.

2021-02-02 08:16 UTC, denisdulici commented on resources/assets/js/components/AkauntingDate.vue
> +import { de } from 'flatpickr/dist/l10n/de.js';
This shouldn't be loaded by default

2021-02-02 08:16 UTC, denisdulici commented on resources/assets/js/components/AkauntingDate.vue
> +            locale: !this.local ? de : en,
What happens if I've set up `fr` in my settings?

2021-02-08 08:48 UTC, denisdulici commented
@tognit Any update on this?

2021-02-08 08:51 UTC, tognit commented
I'm still there

2021-02-08 08:54 UTC, tognit commented on resources/assets/js/components/AkauntingDate.vue
> +import { de } from 'flatpickr/dist/l10n/de.js';
The import should be dynamic according to the locale

2021-02-08 09:05 UTC, tognit commented on resources/assets/js/components/AkauntingDate.vue
> +            locale: !this.local ? de : en,
in date_group.blade.php you could read out the locale
```javascript
<akaunting-date
.......
      :config="{
            ...........
            locale: '{{ language()->getShortCode() }}',
        }"
..........
></akaunting-date>
```

2021-02-13 18:44 UTC, tognit commented
The last update should dynamically adapt the language

2021-02-23 19:08 UTC, merged